### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by TonySchaufelberger** [totenk0pf/13CPT-python#1]
Will there be a version for linux? The "xpnative" theme for ttk is not compatible with linux distros. I have to edit the code to be able to test it on my laptop.

**Comment by totenk0pf** [comment]
The current usage of the "xpnative" theme is a placeholder since I was testing out preset themes, and will be removed in the next commit. My plan is to just define all of the themes in a list and load them in when needed, which will be very much compatible with Linux.
